spring.application.name=demo

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/internship
spring.datasource.username=intership_app
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

# Thymeleaf (DEV MODE)
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.web.resources.static-locations=classpath:/static/,file:uploads/


# Show detailed errors (IMPORTANT FOR DEBUGGING)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

# Thymeleaf (explicit)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html